# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-05 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveme3', '0002_auto_20170531_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='value',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='votedtrait',
            old_name='value',
            new_name='vote',
        ),
    ]
